/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.extreamsd.usbtester;

public class AudioChannelVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AudioChannelVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AudioChannelVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        USBTestNativeJNI.delete_AudioChannelVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AudioChannelVector() {
    this(USBTestNativeJNI.new_AudioChannelVector__SWIG_0(), true);
  }

  public AudioChannelVector(long n) {
    this(USBTestNativeJNI.new_AudioChannelVector__SWIG_1(n), true);
  }

  public long size() {
    return USBTestNativeJNI.AudioChannelVector_size(swigCPtr, this);
  }

  public long capacity() {
    return USBTestNativeJNI.AudioChannelVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    USBTestNativeJNI.AudioChannelVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return USBTestNativeJNI.AudioChannelVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    USBTestNativeJNI.AudioChannelVector_clear(swigCPtr, this);
  }

  public void add(AudioChannel x) {
    USBTestNativeJNI.AudioChannelVector_add(swigCPtr, this, AudioChannel.getCPtr(x), x);
  }

  public AudioChannel get(int i) {
    long cPtr = USBTestNativeJNI.AudioChannelVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new AudioChannel(cPtr, false);
  }

  public void set(int i, AudioChannel val) {
    USBTestNativeJNI.AudioChannelVector_set(swigCPtr, this, i, AudioChannel.getCPtr(val), val);
  }

}
