/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.extreamsd.usbtester;

public class IVolumeControllerVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IVolumeControllerVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IVolumeControllerVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        USBTestNativeJNI.delete_IVolumeControllerVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IVolumeControllerVector() {
    this(USBTestNativeJNI.new_IVolumeControllerVector__SWIG_0(), true);
  }

  public IVolumeControllerVector(long n) {
    this(USBTestNativeJNI.new_IVolumeControllerVector__SWIG_1(n), true);
  }

  public long size() {
    return USBTestNativeJNI.IVolumeControllerVector_size(swigCPtr, this);
  }

  public long capacity() {
    return USBTestNativeJNI.IVolumeControllerVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    USBTestNativeJNI.IVolumeControllerVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return USBTestNativeJNI.IVolumeControllerVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    USBTestNativeJNI.IVolumeControllerVector_clear(swigCPtr, this);
  }

  public void add(IVolumeController x) {
    USBTestNativeJNI.IVolumeControllerVector_add(swigCPtr, this, IVolumeController.getCPtr(x), x);
  }

  public IVolumeController get(int i) {
    long cPtr = USBTestNativeJNI.IVolumeControllerVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new IVolumeController(cPtr, false);
  }

  public void set(int i, IVolumeController val) {
    USBTestNativeJNI.IVolumeControllerVector_set(swigCPtr, this, i, IVolumeController.getCPtr(val), val);
  }

}
